name: "docker"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "*.md"

jobs:
  docker:
    runs-on: "ubuntu-22.04"
    steps:
      - id: "checkout"
        name: "checks out the repository"
        uses: "actions/checkout@v2"

      - id: "qemu"
        name: "sets up a QEMU emulator"
        uses: "docker/setup-qemu-action@v2"

      - id: "buildx"
        name: "sets up a BuildX environment"
        uses: "docker/setup-buildx-action@v2"

      - id: "login"
        name: "logs in to Docker Hub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
